### ISSUE TITLE
ER diagram

### ISSUE THREAD

**Issue by jaanos** [LeaTehovnik/krompir1#1]
Vidim, da imate na ER diagramu veliko relacij `JE`. Če želite res imeti vse tipe hrane kot entitete, potem raje naredite hierarhično delitev hrane na kategorije. Tako bo mogoče za vsako kategorijo imeti svoje atribute in relacije. Če pa teh ne potrebujete, lahko te kategorije predstavite bodisi kot en atribut (če se med seboj izključujejo), ali pa za vsako kategorijo atribut (ki bo tipa `boolean`).

Prav tako ni smiselno, da imate "izpeljane" entitete - torej take, ki so odvisne od vrednosti nekega atributa. Namesto tega bo vsa hrana imela atrbute o vsebnosti beljakovin, maščob itd., potem pa lahko na teh podatkih delate poizvedbe - seveda si jih lahko tudi shranite kot poglede.

**Comment by LeaTehovnik** [comment]
Smo popravile, edino količino smo dale kar k relaciji potrebujemo, saj se nam je zdelo bolj smiselno (na vajah smo tudi dali k relaciji delo - čas). Je to ok?

**Comment by jaanos** [comment]
Tako, količina seveda spada k relaciji. Drugih pripomb nimam, tako da zapiram zadevo.
